# Generated by Django 4.0.2 on 2022-02-22 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessages',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
