# Generated by Django 4.0.2 on 2022-02-22 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_groupmessages_date_groupmessages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 22, 11, 27, 24, 264011, tzinfo=utc)),
        ),
    ]
