# Generated by Django 4.0.2 on 2022-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_groupchat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='messages',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
