# Generated by Django 4.0.2 on 2022-02-22 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_groupmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 22, 11, 34, 45, 286507, tzinfo=utc)),
        ),
    ]
