# Generated by Django 4.0.2 on 2022-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_groupchat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='messages',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
