# Generated by Django 4.0.2 on 2022-02-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_groupchat_group_alter_groupchat_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='messages',
        ),
    ]
