# Generated by Django 4.0.2 on 2022-02-22 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_groupmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 22, 19, 53, 32, 416659)),
        ),
    ]
