# Generated by Django 4.0.2 on 2022-02-22 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_groupmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='date',
            field=models.DateField(verbose_name=datetime.time(16, 33, 31, 847280)),
        ),
    ]
